name: DPD Plugin Fitness Function
description: Validate DPD buildkite plugins standards (and release diff plugin?)
author: Ama Asare <change when moving repos>, DPD
requirements:
  - docker
configuration:
  properties: {}