steps:
  - label: '::exploding_head: when you take your own medicine'
    command: verify-fitness
    plugins:
      - https://github.com/amasare/dpd-plugin-support:
          pluginsource: https://github.com/amasare/dpd-plugin-fitness-function
    agents: 
      queue: 'base-agent' 

  - label: ':zany_face: when you take your own medicine'
    command: release
    plugins:
      - https://github.com/amasare/dpd-plugin-support:
          pluginsource: https://github.com/amasare/dpd-plugin-fitness-function
    agents: 
      queue: 'base-agent'

